"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[⏺](bold green)'
vimcmd_replace_one_symbol = '[⏺](bold purple)'
vimcmd_replace_symbol = '[⏺](bold purple)'
vimcmd_visual_symbol = '[⏺](bold yellow)'

[ruby]
detect_variables = []

[dotnet]
symbol = " "
detect_extensions = [ "csproj", "fsproj", "xproj", "sln" ]

[username]
format = '[$user]($style) '
style_user = 'bold blue'
show_always = true
